argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  batch_size:
    bind_to: processor_cfg.batch_size
    type: int
  gpu_batch_size:
    bind_to: processor_cfg.gpu_batch_size
  checkpoint:
    bind_to: processor_cfg.checkpoint
    help: the checkpoint file to load from
    default: mmskeleton://st_gcn/ntu-xsub

processor_cfg:
  type: "processor.recognition.test"
  checkpoint:

  # model setting
  model_cfg:
    type: "models.backbones.ST_GCN_18"
    in_channels: 3
    num_class: 219
    dropout: 0.5
    edge_importance_weighting: True
    graph_cfg:
      layout: "azure_upper"
      strategy: "spatial"

  # dataset setting
  dataset_cfg:
    type: 'deprecated.datasets.skeleton_feeder.SkeletonFeeder'
    data_path: ./data/view0_rh_aa_val_data.npy
    label_path: ./data/view0_rh_aa_val_label.pkl
    # debug: true

  # dataloader setting
  batch_size: null
  gpu_batch_size: 16
  gpus: -1

